# Generated by Django 5.0.4 on 2024-09-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0011_profileaccount_encryptedfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileaccount',
            name='encryptedField',
        ),
    ]
